### PR TITLE
Windows Compatibility Version

### PR DESCRIPTION
**Pull request by Jaaziel-Polanco**
This pull request introduces changes to ensure optimal functionality of the app on Windows. Features such as file saving and app background styles were incompatible with Windows as they were originally designed for macOS. These changes aim to make the app seamlessly usable across different operating systems.

### CODE REVIEW

**Comment by Jaaziel-Polanco** [comment]
happy to make this contribution

**Comment by Jaaziel-Polanco** [comment]
new branch for window version or merge if working fine for mac

**Review by gionathas — COMMENTED** [review]
Thanks for the PR @Jaaziel-Polanco 🙏 

Anyway in order to not introduce changes that differs from the source code explained in the original tutorial, I won't merge it but I'll refer to this PR to everyone whose need to make it work on  Windows.

Thanks for the contribution.

**Comment by Jaaziel-Polanco** [comment]
You're welcome, in the end I wanted the merger to get the github contributor badge 😢

**Pull request closed without merging**
